version: '3.8'

services:
   db:
    image: mysql:5.7
    volumes:
      # See https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#configure-multi-container-apps
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      # Fetching the password from the application settings
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

   ghost:
    image: andrewmatveychuk/ghost-ai:latest
    depends_on:
      - db
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/content_files:/var/lib/ghost/content_files
    restart: always
    ports:
      - 80:2368
    environment:
      # See https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DATABASE_PASSWORD}
      database__connection__database: ghost